version: '3.7'
services:
    # my-mongodb:
    #     image: mongo:5.0.3
    #     container_name: my-mongodb-name
    #     ports:
    #         - 27017:27017
    #     environment:
    #         MONGO_INITDB_DATABASE: test
    #         MONGO_INITDB_ROOT_USERNAME: admin
    #         MONGO_INITDB_ROOT_PASSWORD: admin
    #     volumes: 
    #         - ./mongodb/data/db:/data/db
    #         - ./mongodb/data/configdb:/data/configdb
    #     networks:
    #         - cluster-network

    spring-service:
        image: spring-service:v1
        container_name: spring-service-name
        restart: always
        ports:
            - "8081:8081"
        environment:
            - spring.data.mongodb.database=test-db
            # - spring.data.mongodb.uri=mongodb://admin:admin@my-mongodb:27017/test    # for local mongo  
            - spring.data.mongodb.uri=mongodb+srv://readonly:readonly@cluster-longpt.ocem8.mongodb.net/test
            - logging.level.org.springframework.data=debug
            - logging.level.=error

        networks:
            - cluster-network
        # depends_on:
            # - my-mongodb

    medical-module:
        image: medical-module:v1
        container_name: medical-module-name
        restart: always
        ports:
            - "8083:8083"
        networks:
            - cluster-network
    mongodb:
        image: mongo
        container_name: mongodb-name
        environment:
            - PUID=1000
            - PGID=1000
        volumes:
            - ./mongodb/data/db:/data/db
        ports:
            - "27017:27017"
        restart: always
        networks:
            - cluster-network
    keycloak:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak-name
        environment:
            KEYCLOAK_USER: admin
            KEYCLOAK_PASSWORD: admin
        ports:
            -   "8080:8080"
        restart: always
        networks:
            - cluster-network
networks:
    cluster-network:
        driver: bridge